=== jivahire-com/cpp-thread-safe-cache/src/externs/1pfw_fwlibs/temp_copies_of_mu_scripts/configschema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- Copyright (c) Microsoft Corporation. All rights reserved. -->

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="ConfigSchema">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Enums" minOccurs="0" maxOccurs="1">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="Enum" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="Value" maxOccurs="unbounded">
                      <xs:complexType>
                        <xs:attribute name="name" use="required" />
                        <xs:attribute name="prettyname" use="optional" />
                        <xs:attribute name="value" use="required" />
                        <xs:attribute name="help" use="optional" />
                        <xs:attribute name="deprecated" type="xs:boolean" use="optional" />
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                  <xs:attribute name="name" use="required" />
                  <xs:attribute name="prettyname" use="optional" />
                  <xs:attribute name="default" use="optional" />
                  <xs:attribute name="help" use="optional" />
                  <xs:attribute name="headerRef" use="optional" />
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="Structs" minOccurs="0" maxOccurs="1">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="Struct" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="Member" maxOccurs="unbounded">
                      <xs:complexType>
                        <xs:attribute name="name" use="required" />
                        <xs:attribute name="prettyname" use="optional" />
                        <xs:attribute name="type" use="required" />
                        <xs:attribute name="default" use="optional" />
                        <xs:attribute name="min" use="optional" />
                        <xs:attribute name="max" use="optional" />
                        <xs:attribute name="count" type="xs:integer" use="optional" />
                        <xs:attribute name="help" use="optional" />
                        <xs:attribute name="deprecated" type="xs:boolean" use="optional" />
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                  <xs:attribute name="name" use="required" />
                  <xs:attribute name="prettyname" use="optional" />
                  <xs:attribute name="help" use="optional" />
                  <xs:attribute name="headerRef" use="optional" />
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="Knobs" minOccurs="1" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:choice maxOccurs="unbounded">
                <xs:element name="Knob" maxOccurs="unbounded">
                  <xs:complexType>
                    <xs:attribute name="name" use="required" />
                    <xs:attribute name="prettyname" use="optional" />
                    <xs:attribute name="type" use="required" />
                    <xs:attribute name="default" use="optional" />
                    <xs:attribute name="min" use="optional" />
                    <xs:attribute name="max" use="optional" />
                    <xs:attribute name="help" use="optional" />
                    <xs:attribute name="deprecated" type="xs:boolean" use="optional" />
                  </xs:complexType>
                </xs:element> 
              </xs:choice>
            </xs:sequence>
            <xs:attribute name="namespace" use="required" />
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== jivahire-com/cpp-thread-safe-cache/config/knobs_config/kng_mscp_pcie_config_knobs.xml
<ConfigSchema xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="configschema.xsd">

  <!-- Enum values are declared separately from the knobs.
  The same Enum can be used as the 'enumtype' of any number of EnumKnobs -->
  <Enums>
  </Enums>

  <Structs>
    <Struct name="pcie_prod_cfg_t" help="Available knobs to configure the RPSS in prod FW">
      <Member name="pcie_ss_en" type="bool" default="true" help="Set to false to force disable the pciess block" />
      <Member name="pcie_bifurcation_mode" type="PCIE_BIFURCATION_MODE" default="PCIE_BIFURCATION_1X16" help="Bifurcation Mode config for PCIeSS" />
      <Member name="pcie_clock_mode" type="PCIE_CLOCK_MODE" default="PCIE_CLOCK_SRIS" help="Link Clock Mode config for PCIeSS" />
      <Member name="pcie_stagger_time" type="PCIE_STAGGER_TIME" default="PCIE_STAGGER_NONE" help="Lane Stagger Time config for PCIeSS" />
      <Member name="pcie_aspm_support" type="PCIE_ASPM_SUPPORT" default="PCIE_L1_SUPPORT" help="Feature support mode for PCIe ASPM" />
      <Member name="pcie_ltr_support" type="bool" default="true" help="LTR Support for PCIeSS" />
      <Member name="pcie_l1_exit_latency" type="PCIE_L1_EXIT_LATENCY" default="PCIE_L1_LATENCY_32_TO_64_US" help="L1 Exit Latency for PCIeSS" />
      <Member name="pcie_l0s_exit_latency" type="PCIE_L0S_EXIT_LATENCY" default="PCIE_L0S_LATENCY_2_TO_4_US" help="L0s Exit Latency for PCIeSS" />
      <Member name="pcie_loopback_mode" type="PCIE_LOOPBACK_MODE" default="PCIE_LOOPBACK_NONE" help="Loopback operation mode for PCIeSS" />
      <Member name="pcie_cap_gen_speed" type="PCIE_GEN_SPEED" default="PCIE_GEN_1" help="Maximum supported PCIe Gen speed for PCIeSS" />
      <Member name="pcie_cap_mps" type="PCIE_MAX_PAYLOAD_SIZE" default="PCIE_MAX_128B_SIZE" help="Maximum supported Payload Size (MPS) for PCIeSS" />
      <Member name="pcie_rcb_mode" type="PCIE_RCB_MODE" default="PCIE_RP_RCB_64B" help="Read Completion Boundary (RCB) config for PCIeSS" />
      <Member name="pcie_ras_mode" type="PCIE_RAS_MODE" default="PCIE_RAS_MODE_EN" help="RAS Operation Mode for PCIeSS" />
      <Member name="pcie_fast_link_mode" type="bool" default="false" help="Enable fast-link-mode for PCIeSS" />
      <Member name="pcie_gen3_eq_disable" type="bool" default="false" help="Disable Gen3 Equalization Phase for PCIeSS" />
      <Member name="pcie_gen4_eq_disable" type="bool" default="false" help="Disable Gen4 Equalization Phase for PCIeSS" />
      <Member name="pcie_gen5_eq_disable" type="bool" default="false" help="Disable Gen5 Equalization Phase for PCIeSS" />
      <Member name="pcie_eq_bypass_support" type="bool" default="false" help="Equalization Bypass Support for PCIeSS" />
      <Member name="pcie_no_eq_support" type="bool" default="false" help="No-Equalization Support for PCIeSS" />
      <Member name="pcie_cxl_support" type="bool" default="false" help="CXL Support for PCIeSS" />
      <Member name="pcie_cxl_sync_header_bypass" type="bool" default="false" help="Sync header bypass for CXL Flex Bus" />
      <Member name="pcie_ide_support" type="bool" default="false" help="IDE Support for PCIeSS" />
      <Member name="pcie_tee_support" type="bool" default="false" help="TEE Support for PCIeSS. Setting this will implicitly set 'pcie_ide_support'" />
      <Member name="pcie_fips_test" type="PCIE_FIPS_TEST" default="PCIE_FIPS_NO_TEST" help="When TEE Support is enabled, this knob controls the behavior of FIPS testing." />
      <Member name="pcie_ide_rekey_support" type="bool" default="false" help="IDE Rekeying Support for PCIeSS" />
      <Member name="pcie_ide_sync_msg_threshold" type="uint16_t" default="251" help="IDE Sync Message Threshold for PCIeSS" />
      <Member name="pcie_msi_ext_data_support" type="bool" default="true" help="MSI Extended Data Support for PCIeSS" />
      <Member name="pcie_msi_64bit_support" type="bool" default="true" help="64-bit MSI Address Support for PCIeSS" />
      <Member name="pcie_system_counter_delay" type="uint32_t" default="0" help="System counter delay for various RPSS instances" />
      <Member name="pcie_aer_ecrc_gen_support" type="bool" default="true" help="AER ECRC Generation Support for PCIeSS" />
      <Member name="pcie_aer_ecrc_check_support" type="bool" default="true" help="AER ECRC Check Support for PCIeSS" />
      <Member name="pcie_aer_multiple_header_support" type="bool" default="true" help="AER Muliple-Header Support for PCIeSS" />
    </Struct>
  </Structs>

  <!-- namespace indicates the GUID namespace the values are stored in -->
  <Knobs namespace="{FE3ED49F-B173-41ED-9076-356661D46A42}">
    <!-- PCIe -->
    <Knob name="die1_rpss_enabled" type="bool" default="true" help="Set to false to disable die1 RPSS instances"/>
    <Knob name="pcie_rpss0_cfg" type="pcie_prod_cfg_t" />
    <Knob name="pcie_rpss0_rp0_cfg" type="pcie_rp_cfg_t" />
    <Knob name="pcie_rpss0_rp1_cfg" type="pcie_rp_cfg_t" />
    <Knob name="pcie_rpss0_rp2_cfg" type="pcie_rp_cfg_t" />
    <Knob name="pcie_rpss0_rp3_cfg" type="pcie_rp_cfg_t" />

    <Knob name="pcie_rpss1_cfg" type="pcie_prod_cfg_t" />
    <Knob name="pcie_rpss1_rp0_cfg" type="pcie_rp_cfg_t" />
    <Knob name="pcie_rpss1_rp1_cfg" type="pcie_rp_cfg_t" />
    <Knob name="pcie_rpss1_rp2_cfg" type="pcie_rp_cfg_t" />
    <Knob name="pcie_rpss1_rp3_cfg" type="pcie_rp_cfg_t" />

    <Knob name="pcie_rpss2_cfg" type="pcie_prod_cfg_t" />
    <Knob name="pcie_rpss2_rp0_cfg" type="pcie_rp_cfg_t" />
    <Knob name="pcie_rpss2_rp1_cfg" type="pcie_rp_cfg_t" />
    <Knob name="pcie_rpss2_rp2_cfg" type="pcie_rp_cfg_t" />
    <Knob name="pcie_rpss2_rp3_cfg" type="pcie_rp_cfg_t" />

    <Knob name="pcie_rpss3_cfg" type="pcie_prod_cfg_t" />
    <Knob name="pcie_rpss3_rp0_cfg" type="pcie_rp_cfg_t" />
    <Knob name="pcie_rpss3_rp1_cfg" type="pcie_rp_cfg_t" />
    <Knob name="pcie_rpss3_rp2_cfg" type="pcie_rp_cfg_t" />
    <Knob name="pcie_rpss3_rp3_cfg" type="pcie_rp_cfg_t" />

    <Knob name="pcie_rpss4_cfg" type="pcie_prod_cfg_t" />
    <Knob name="pcie_rpss4_rp0_cfg" type="pcie_rp_cfg_t" />
    <Knob name="pcie_rpss4_rp1_cfg" type="pcie_rp_cfg_t" />
    <Knob name="pcie_rpss4_rp2_cfg" type="pcie_rp_cfg_t" />
    <Knob name="pcie_rpss4_rp3_cfg" type="pcie_rp_cfg_t" />

    <Knob name="pcie_rpss5_cfg" type="pcie_prod_cfg_t" />
    <Knob name="pcie_rpss5_rp0_cfg" type="pcie_rp_cfg_t" />
    <Knob name="pcie_rpss5_rp1_cfg" type="pcie_rp_cfg_t" />
    <Knob name="pcie_rpss5_rp2_cfg" type="pcie_rp_cfg_t" />
    <Knob name="pcie_rpss5_rp3_cfg" type="pcie_rp_cfg_t" />

    <Knob name="pcie_rpss6_cfg" type="pcie_prod_cfg_t" />
    <Knob name="pcie_rpss6_rp0_cfg" type="pcie_rp_cfg_t" />
    <Knob name="pcie_rpss6_rp1_cfg" type="pcie_rp_cfg_t" />
    <Knob name="pcie_rpss6_rp2_cfg" type="pcie_rp_cfg_t" />
    <Knob name="pcie_rpss6_rp3_cfg" type="pcie_rp_cfg_t" />

    <Knob name="pcie_rpss7_cfg" type="pcie_prod_cfg_t" />
    <Knob name="pcie_rpss7_rp0_cfg" type="pcie_rp_cfg_t" />
    <Knob name="pcie_rpss7_rp1_cfg" type="pcie_rp_cfg_t" />
    <Knob name="pcie_rpss7_rp2_cfg" type="pcie_rp_cfg_t" />
    <Knob name="pcie_rpss7_rp3_cfg" type="pcie_rp_cfg_t" />
  </Knobs>

</ConfigSchema>

=== jivahire-com/cpp-thread-safe-cache/config/knobs_config/kng_mscp_mesh_config_knobs.xml
<ConfigSchema xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="configschema.xsd">

  <!-- Enum values are declared separately from the knobs.
  The same Enum can be used as the 'enumtype' of any number of EnumKnobs -->
  <Enums>
  </Enums>

  <Structs>
    <Struct name="mesh_hni_cfg_ctl_t" help="">
      <Member name="mesh_hni_cfg_ctl" type="uint64_t" count="6" help="Set HN-I Config CTL value"/>
    </Struct>
    <Struct name="mesh_hni_aux_ctl_t" help="">
      <Member name="mesh_hni_aux_ctl" type="uint64_t" count="6" help="Set HN-I AUX ctl value"/>
    </Struct>
    <Struct name="mesh_rni_cfg_ctl_t" help="">
      <Member name="mesh_rni_cfg_ctl" type="uint64_t" count="8" help="Set RN-I config control value(chip_id field will be ignored)"/>
    </Struct>
    <Struct name="mesh_rni_aux_ctl_t" help="">
      <Member name="mesh_rni_aux_ctl" type="uint64_t" count="8" help="Set RN-I auxiliary control value"/>
    </Struct>
    <Struct name="mesh_rnd_cfg_ctl_t" help="">
      <Member name="mesh_rnd_cfg_ctl" type="uint64_t" count="7" help="Set RN-D config control value(chip_id field will be ignored)e"/>
    </Struct>
    <Struct name="mesh_rnd_aux_ctl_t" help="">
      <Member name="mesh_rnd_aux_ctl" type="uint64_t" count="7" help="Set RN-D auxiliary control value"/>
    </Struct>
  </Structs>

  <!-- namespace indicates the GUID namespace the values are stored in -->
  <Knobs namespace="{FE3ED49F-B173-41ED-9076-356661D46A42}">
    <!-- Mesh Sequence -->
    <Knob name="mesh_d2d_override" type="bool" default="false" help="Enable and Use the Mesh D2D Knobs listed" />
    <Knob name="cmn_sam_config" type="CMN_SAM_CONFIG_TYPE" default="CMN_SAM_CONFIG_1D_UMA_64HNS_HIER_3SN" help="Select Mesh config" />
    <Knob name="cmn_cxl_interleave" type="uint8_t" default="0" help="Selct CXL intearleave value 0,3 or 4" />
    <Knob name="cmn_cxl_device_interleave_size" type="uint8_t" default="2" help="This field controls the interleave size across all aggregated CXSA/CXLSA Devices 4'h0: 64B Interleaved 4'h1: 128B Interleaved 4'h2: 256B Interleaved 4'h3: 512B Interleaved 4'h4: 1KB Interleaved 4'h5: 2KB Interleaved 4'h6: 4KB Interleaved 4'h7: 8KB Interleaved 4'h8: 16KB" />
    <Knob name="cmn_uma_arsm_htg_wa_disabled" type="uint8_t" default="0" help="Set value for UMA ARSM HTG CFG" />

    <!-- Mesh -->
    <Knob name="mesh_hnf_cbusy_limit_ctl" type="uint64_t" default="0x302010" help="Cbusy threshold limits for POCQ entries"/>
    <Knob name="mesh_hnf_cbusy_resp_ctl" type="uint64_t" default="0x180400800040000" help="Contols the responses sent from HNS to RNF"/>
    <Knob name="mesh_hnf_cbusy_sn_ctl" type="uint64_t" default="0x100001000200040" help="Controls the SN-F cbusy thresholds."/>
    <Knob name="mesh_hnf_cbusy_write_limit_ctl" type="uint64_t" default="0x302010" help="Cbusy threshold limits for POCQ write entries."/>
    <Knob name="mesh_hnf_cbusy_mode_ctl" type="uint64_t" default="0x3000" help="Control register for additional CBusy controls"/>
    <Knob name="mesh_hnf_aux_ctl" type="uint64_t" default="0x2000001000200002" help="Auxiliary control register for HNF. Default val 0x2000_0010_0020_0002"/>
    <Knob name="mesh_hnf_r2_aux_ctl" type="uint64_t" default="0x3001005A900" help="Set value for por_hnf_aux_ctl_1"/>
    <Knob name="mesh_hnf_cfg_ctl" type="uint64_t" default="0x2000C017389A3000" help="Set value for por_hnf_cfg_ctl"/>
    <Knob name="mesh_hnf_lbt_cfg_ctl" type="uint64_t" default="0x7F7F00" help="Functions as the configuration control register for HN-F. Only applicable to LBT transactions"/>
    <Knob name="mesh_hnf_lbt_aux_ctl" type="uint64_t" default="0x440000000000006" help="Functions as the auxiliary control register for HN-F. Only applicable to LBT transactions"/>
    <Knob name="mesh_hnf_lbt_cbusy_ctl" type="uint64_t" default="0x0" help="Controls the CBusy response for LCN Bound Transactions"/>
    <Knob name="mesh_hni_cfg_ctl_knob" type="mesh_hni_cfg_ctl_t" default="{{0x1,0x1,0x1,0x1,0x1,0x1}}" help="Set HN-I Config CTL value"/>
    <Knob name="mesh_hni_aux_ctl_knob" type="mesh_hni_aux_ctl_t" default="{{0x1000,0x1000,0x1000,0x1000,0x1000,0x1000}}" help="Set HN-I AUX ctl value"/>
    <Knob name="mesh_hnt_dn_domain_cxra" type="uint64_t" default="0" help="Set value for cxra per HNT (There are 4 HNTs)"/>
    <Knob name="mesh_rni_cfg_ctl_knob" type="mesh_rni_cfg_ctl_t" default="{{0xd000802001c21,0xd000802001c21,0xd000802001c21,0xd000802001c21,0xd004200401c41,0xd000802001c71,0xd000802001c71,0xd000802001c71}}" help="Set RN-I config control value(chip_id field will be ignored)"/>
    <Knob name="mesh_rni_aux_ctl_knob" type="mesh_rni_aux_ctl_t" default="{{0x4004002,0x4004002,0x4004002,0x4004002,0x4004002,0x4004002,0x4004002,0x4004002}}" help="Set RN-I auxiliary control value"/>
    <Knob name="mesh_rnd_cfg_ctl_knob" type="mesh_rnd_cfg_ctl_t" default="{{0xd000802001c21,0xd000802001c01,0xd000802001c21,0xd000802001c21,0xd000802001c21,0xd000200401c01,0xd000802001c01}}" help="Set RN-D config control value(chip_id field will be ignored)"/>
    <Knob name="mesh_rnd_aux_ctl_knob" type="mesh_rnd_aux_ctl_t" default="{{0x4004012,0x4004012,0x4004012,0x4004012,0x4004012,0x4004012,0x4004012}}" help="Set RN-D auxiliary control value"/>

    <!-- Mesh RAS -->
    <Knob name="mesh_RAS_Error_Detection_Disable" type="bool" default="0" help="If true, disable Mesh RAS Error Detection in the Mesh RAS Control registers. Default: false."/>
    <Knob name="mesh_RAS_Error_Deferment_Disable" type="bool" default="0" help="If true, disable Mesh RAS Error Deferment in the Mesh RAS Control registers. Default: false."/>
    <Knob name="mesh_RAS_Uncorrected_Error_Int_Disable" type="bool" default="0" help="If true, disable Mesh RAS Uncorrected Error Interrupt in the Mesh RAS Control registers. Default: false."/>
    <Knob name="mesh_RAS_Fault_Handling_Int_Disable" type="bool" default="0" help="If true, disable Mesh RAS Fault Handling Interrupt in the Mesh RAS Control registers. Default: false."/>
    <Knob name="mesh_RAS_Corrected_Error_Int_Disable" type="bool" default="1" help="If true, disable Mesh RAS Corrected Error Interrupt in the Mesh RAS Control registers. Default: true."/>
    <Knob name="mesh_RAS_Parity_Error_Disable" type="bool" default="1" help="If true, disable External Logging Parity Errors in the Mesh RAS Control registers. Default: false."/>

    <!-- Mesh CCG -->
    <Knob name="por_ccg_ha_aux_ctl" type="uint64_t" default="0x3C0008" help="CCG HA aux control"/>
    <Knob name="por_ccg_ha_cfg_ctl" type="uint64_t" default="0x40040" help="CCG HA config control"/>
    <Knob name="por_ccg_ha_cxprtcl_link0_ctl" type="uint64_t" default="0x1C0000" help="CCG HA config control 1"/>
    <Knob name="por_ccg_ra_cfg_ctl" type="uint64_t" default="0x7C1007" help="CCG RA config control"/>
    <Knob name="por_ccg_ra_aux_ctl" type="uint64_t" default="0x1B1F343CC3846" help="CCG RA aux control"/>
    <Knob name="por_ccg_ra_ccprtcl_link0_ctl" type="uint64_t" default="0x2C00000" help="CCG RA config control 1"/>
    <Knob name="por_ccg_ra_cbusy_limit_ctl" type="uint64_t" default="0x181008" help="CCG RA config control 2"/>
    <Knob name="por_ccla_aux_ctl" type="uint64_t" default="0x1220000000004" help="CCLA aux control"/>

    <!-- Mesh D2D -->
    <Knob name="d2d_pll_divder" type="uint8_t" default="2" help="txdiv field in d2dConfig2"/>
    <Knob name="d2d_ref_divder" type="uint8_t" default="2" help="Reference clock value(1-15)"/>
    <Knob name="d2d_pll_fb_devider" type="uint8_t" default="0x14" help="feedback clock devide value (1-127)"/>
    <Knob name="d2d_ecc_cfg" type="uint8_t" default="0" help="Configure Bit 9 and 10 of D2D Config to enable or disable RX/TX ECC "/>
    <Knob name="d2d_tx_interface_clk_alignment" type="uint32_t" default="0" help="run calibration to center TX interface"/>
    <Knob name="d2d_ras_enable" type="uint8_t" default="0" help="Enable RAS"/>
    <Knob name="d2d_sleep_cfg" type="uint8_t" default="1" help="Sleep configuration 1: enable 0:disable"/>
    <Knob name="d2d_sleep_cfg_entry" type="uint32_t" default="0" help="Sleep configuration entry: Idle entry time, Number of clock cycle the channel must be Idle"/>
    <Knob name="d2d_rxcal_find_goodlanes_skip" type="bool" default="1"/>
  </Knobs>

</ConfigSchema>

=== jivahire-com/cpp-thread-safe-cache/config/knobs_config/kng_mscp_clock_sequence_knobs.xml
<ConfigSchema xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="configschema.xsd">

  <!-- Enum values are declared separately from the knobs.
       The same Enum can be used as the 'enumtype' of any number of EnumKnobs -->
  <Enums>
  </Enums>

  <Structs>
    <Struct name="clocks_sequence_knobs_t">
      <Member name="clocks_intclk_cfg" type="intclk_cfg_t" count="1" help="Int-clk frequency configuration" />
      <Member name="sys_counter_delay_cfg" type="sys_counter_delay_cfg_t" count="1" help="System counter delay config for msxp and dbgroot" />
    </Struct>
  </Structs>

  <!-- namespace indicates the GUID namespace the values are stored in -->
  <Knobs namespace="{FE3ED49F-B173-41ED-9076-356661D46A42}">
    <!-- clocks sequence -->
    <Knob name="clock_seq_knobs" type="clocks_sequence_knobs_t" help="Clocks sequence knobs" />
  </Knobs>

</ConfigSchema>

=== jivahire-com/cpp-thread-safe-cache/config/knobs_config/kng_mscp_power_tlm_knobs.xml
<ConfigSchema xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="configschema.xsd">

  <!-- Enum values are declared separately from the knobs.
       The same Enum can be used as the 'enumtype' of any number of EnumKnobs -->
  <Enums>
    <Enum name="power_tlm_inst_sample_period_t" help="">
      <Value name="PWR_TLM_INST_SAMPLE_PERIOD_5_MS" prettyname="5 mS" value="1" help="create inst record's every 5 mS" />
      <Value name="PWR_TLM_INST_SAMPLE_PERIOD_10_MS" prettyname="10 mS" value="2" help="create inst record's every 10 mS" />
      <Value name="PWR_TLM_INST_SAMPLE_PERIOD_20_MS" prettyname="20 mS" value="4" help="create inst record's every 20 mS" />
      <Value name="PWR_TLM_INST_SAMPLE_PERIOD_40_MS" prettyname="40 mS" value="8" help="create inst record's every 40 mS" />
      <Value name="PWR_TLM_INST_SAMPLE_PERIOD_100_MS" prettyname="100 mS" value="20" help="create inst record's every 100 mS" />
    </Enum>
    <Enum name="power_tlm_prod_package_period_t" help="">
      <Value name="PWR_TLM_PROD_PKG_PERIOD_30_SEC" prettyname="30 seconds" value="1" help="create production package every 30 sec" />
      <Value name="PWR_TLM_PROD_PKG_PERIOD_1_MIN" prettyname="1 minute" value="2" help="create production package every minute" />
      <Value name="PWR_TLM_PROD_PKG_PERIOD_2_MIN" prettyname="2 minute" value="3" help="create production package every 2 minutes" />
    </Enum>
    <Enum name="power_tlm_24hr_package_period_t" help="">
      <Value name="PWR_TLM_24HR_PKG_PERIOD_24_HR" prettyname="24 hours" value="1" help="create production package every 24 hours" />
      <Value name="PWR_TLM_24HR_PKG_PERIOD_60_MIN" prettyname="60 minutes" value="2" help="create production package every 60 minutes" />
      <Value name="PWR_TLM_24HR_PKG_PERIOD_30_MIN" prettyname="30 minutes" value="3" help="create production package every 30 minutess" />
    </Enum>
  </Enums>

  <Structs>
    <Struct name="power_tlm_knobs_t" help="">
      <Member name="inst_sample_period" type="power_tlm_inst_sample_period_t" default="PWR_TLM_INST_SAMPLE_PERIOD_10_MS" help="Inst Record Sampling Period" />
      <Member name="prod_pkg_period" type="power_tlm_prod_package_period_t" default="PWR_TLM_PROD_PKG_PERIOD_2_MIN" help="Production Package Period" />
      <Member name="inst_samples_per_pkg" type="uint16_t" default="10" help="Package generated every n inst_sample_period" />
      <Member name="_24hr_sample_period" type="power_tlm_24hr_package_period_t" default="PWR_TLM_24HR_PKG_PERIOD_24_HR" help="24 Hr Package Sampling Period" />
    </Struct>
  </Structs>

  <!-- namespace indicates the GUID namespace the values are stored in -->
  <Knobs namespace="{FE3ED49F-B173-41ED-9076-356661D46A42}">
    <Knob name="pwr_tlm_knobs" type="power_tlm_knobs_t" help="Power Telemetry knobs"/>
  </Knobs>

</ConfigSchema>
