=== jivahire-com/cpp-thread-safe-cache/src/externs/1pfw_fwlibs/temp_copies_of_mu_scripts/configschema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- Copyright (c) Microsoft Corporation. All rights reserved. -->

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="ConfigSchema">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Enums" minOccurs="0" maxOccurs="1">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="Enum" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="Value" maxOccurs="unbounded">
                      <xs:complexType>
                        <xs:attribute name="name" use="required" />
                        <xs:attribute name="prettyname" use="optional" />
                        <xs:attribute name="value" use="required" />
                        <xs:attribute name="help" use="optional" />
                        <xs:attribute name="deprecated" type="xs:boolean" use="optional" />
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                  <xs:attribute name="name" use="required" />
                  <xs:attribute name="prettyname" use="optional" />
                  <xs:attribute name="default" use="optional" />
                  <xs:attribute name="help" use="optional" />
                  <xs:attribute name="headerRef" use="optional" />
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="Structs" minOccurs="0" maxOccurs="1">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="Struct" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="Member" maxOccurs="unbounded">
                      <xs:complexType>
                        <xs:attribute name="name" use="required" />
                        <xs:attribute name="prettyname" use="optional" />
                        <xs:attribute name="type" use="required" />
                        <xs:attribute name="default" use="optional" />
                        <xs:attribute name="min" use="optional" />
                        <xs:attribute name="max" use="optional" />
                        <xs:attribute name="count" type="xs:integer" use="optional" />
                        <xs:attribute name="help" use="optional" />
                        <xs:attribute name="deprecated" type="xs:boolean" use="optional" />
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                  <xs:attribute name="name" use="required" />
                  <xs:attribute name="prettyname" use="optional" />
                  <xs:attribute name="help" use="optional" />
                  <xs:attribute name="headerRef" use="optional" />
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="Knobs" minOccurs="1" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:choice maxOccurs="unbounded">
                <xs:element name="Knob" maxOccurs="unbounded">
                  <xs:complexType>
                    <xs:attribute name="name" use="required" />
                    <xs:attribute name="prettyname" use="optional" />
                    <xs:attribute name="type" use="required" />
                    <xs:attribute name="default" use="optional" />
                    <xs:attribute name="min" use="optional" />
                    <xs:attribute name="max" use="optional" />
                    <xs:attribute name="help" use="optional" />
                    <xs:attribute name="deprecated" type="xs:boolean" use="optional" />
                  </xs:complexType>
                </xs:element> 
              </xs:choice>
            </xs:sequence>
            <xs:attribute name="namespace" use="required" />
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== jivahire-com/cpp-thread-safe-cache/config/knobs_config/kng_mscp_unit_test_config_knobs.xml
<ConfigSchema xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="configschema.xsd">

  <!-- Enum values are declared separately from the knobs.
       The same Enum can be used as the 'enumtype' of any number of EnumKnobs -->
  <Enums>
    <Enum name="OPTION_MODE" help="Modes of the option">
      <Value name="FIRST" prettyname="First Mode" value="0" help="First mode" />
      <Value name="SECOND" prettyname="Second Mode" value="1" help="Second mode" />
      <Value name="THIRD" prettyname="Third Mode" value="2" help="Third mode" />
    </Enum>
    <Enum name="MODULE_MODE" help="Module modes">
      <Value name="MODEA" prettyname="Mode A" value="0" help="Fast mode" />
      <Value name="MODEB" prettyname="Mode B" value="1" help="Slow mode" />
    </Enum>
  </Enums>

  <Structs>
    <Struct name="simple_t" help="Simple struct">
      <Member name="value" count="2" type="uint32_t" />
    </Struct>
    <Struct name="child_t" prettyname="Child Struct"  help="Embedded struct">
      <Member name="data" prettyname="child Data" type="uint8_t" count="5" help="Bytes" />
      <Member name="mode" type="OPTION_MODE" />
    </Struct>
    <Struct name="sample_t" help="Sample struct">
      <Member name="counter" type="uint32_t" help="Number value" />
      <Member name="children" type="child_t" count="2" help="Child data" />
    </Struct>
  </Structs>

  <!-- namespace indicates the GUID namespace the values are stored in -->
  <Knobs namespace="{FE3ED49F-B173-41ED-9076-356661D46A42}">
    <!-- primative knobs -->
    <Knob type="uint8_t" name="k_uint8_t"  />
    <Knob type="uint8_t" name="k_uint8_t_d10"  default="10" />
    <Knob type="uint8_t" name="k_uint8_t_d10_min5"  default="10" min="5" />
    <Knob type="uint8_t" name="k_uint8_t_d10_max20"  default="10" max="20" />
    <Knob type="uint8_t" name="k_uint8_t_d10_min5_max20"  default="10" min="5" max="20" />

    <Knob type="int8_t" name="k_int8_t" />
    <Knob type="int8_t" name="k_int8_t_d10" default="10" />
    <Knob type="int8_t" name="k_int8_t_dn10" default="-10" />
    <Knob type="int8_t" name="k_int8_t_d10_minn5" min="-5" default="10" />
    <Knob type="int8_t" name="k_int8_t_d10_max20" max="20" default="10" />
    <Knob type="int8_t" name="k_int8_t_d10_minn5_max20" min="-5" max="20" default="10" />

    <Knob type="uint16_t" name="k_uint16_t" />
    <Knob type="uint16_t" name="k_uint16_t_d1000" default="1000" />
    <Knob type="uint16_t" name="k_uint16_t_d1000_min500" default="1000" min="500" />
    <Knob type="uint16_t" name="k_uint16_t_d1000_max2000" default="1000" max="2000" />
    <Knob type="uint16_t" name="k_uint16_t_d1000_min500_max2000" default="1000" min="500" max="2000" />

    <Knob type="int16_t" name="k_int16_t" />
    <Knob type="int16_t" name="k_int16_t_d1000" default="1000" />
    <Knob type="int16_t" name="k_int16_t_dn1000" default="-1000" />
    <Knob type="int16_t" name="k_int16_t_d1000_minn500" default="1000" min="-500" />
    <Knob type="int16_t" name="k_int16_t_d1000_max2000" default="1000" max="2000" />
    <Knob type="int16_t" name="k_int16_t_d1000_minn500_max2000" default="1000" min="-500" max="2000" />
    
    <Knob type="uint32_t" name="k_uint32_t" />
    <Knob type="uint32_t" name="k_uint32_t_d1000000" default="1000000" />
    <Knob type="uint32_t" name="k_uint32_t_d1000000_min500000" default="1000000" min="500000" />
    <Knob type="uint32_t" name="k_uint32_t_d1000000_max2000000" default="1000000" max="2000000" />
    <Knob type="uint32_t" name="k_uint32_t_d1000000_min500000_max2000000" default="1000000" min="500000" max="2000000" />
    
    <Knob type="int32_t" name="k_int32_t" />
    <Knob type="int32_t" name="k_int32_t_d1000000" default="1000000" />
    <Knob type="int32_t" name="k_int32_t_dn1000000" default="-1000000" />
    <Knob type="int32_t" name="k_int32_t_d1000000_minn500000" default="1000000" min="-500000"/>
    <Knob type="int32_t" name="k_int32_t_d1000000_max2000000" default="1000000" max="2000000"/>
    <Knob type="int32_t" name="k_int32_t_d1000000_minn500000_max2000000" default="1000000" min="-500000" max="2000000"/>

    <Knob type="uint64_t" name="k_uint64_t" />
    <Knob type="uint64_t" name="k_uint64_t_d10000000000" default="10000000000" />
    <Knob type="uint64_t" name="k_uint64_t_d10000000000_min5000000000" default="10000000000" min="5000000000" />
    <Knob type="uint64_t" name="k_uint64_t_d10000000000_max20000000000" default="10000000000" max="20000000000" />
    <Knob type="uint64_t" name="k_uint64_t_d10000000000_min5000000000_max20000000000" default="10000000000" min="5000000000" max="20000000000" />
    
    <Knob type="int64_t" name="k_int64_t" />
    <Knob type="int64_t" name="k_int64_t_d10000000000" default="10000000000" />
    <Knob type="int64_t" name="k_int64_t_dn10000000000" default="-10000000000" />
    <Knob type="int64_t" name="k_int64_t_d10000000000_minn5000000000" default="10000000000" min="-5000000000" />
    <Knob type="int64_t" name="k_int64_t_d10000000000_max20000000000" default="10000000000" max="20000000000" />
    <Knob type="int64_t" name="k_int64_t_d10000000000_minn500000000_max20000000000" default="10000000000" min="-5000000000" max="20000000000" />

    <Knob type="float" name="k_float" />
    <Knob type="float" name="k_float_d10_5" default="10.5" />
    <Knob type="float" name="k_float_dn10_5" default="-10.5" />
    <Knob type="float" name="k_float_d10_5_minn5_5" default="10.5" min="-5.5" />
    <Knob type="float" name="k_float_d10_5_max20_5" default="10.5" max="20.5" />
    <Knob type="float" name="k_float_d10_5_minn5_5_max20_5" default="10.5" min="-5.5" max="20.5" />

    <Knob type="double" name="k_double" />
    <Knob type="double" name="k_double_d10_000005" default="10.000005" />
    <Knob type="double" name="k_double_dn10_000005" default="-10.000005" />
    <Knob type="double" name="k_double_d10_5_minn5_5" default="10.5" min="-5.5" />
    <Knob type="double" name="k_double_d10_5_max20_5" default="10.5" max="20.5" />
    <Knob type="double" name="k_double_d10_5_minn5_5_max20_5" default="10.5" min="-5.5" max="20.5" />

    <Knob type="bool" name="k_bool" />
    <Knob type="bool" name="k_bool_dtrue" default="true" />
  
    <Knob name="COMPLEX_ffKNOB1a" type="child_t" default="{{1,2,3, 4,5 },FIRST }" help="Complex knob" />
    <Knob name="COMPLEX_KNOB1b" prettyname="Complex Knob 1b Struct" type="child_t" default="{{1,2,3, 4,5 },SECOND }" help="Complex type" />
    <Knob name="COMPLEX_KNOB2" type="sample_t" default="{2,{{{1,2,3, 4,5 },FIRST },{{6,7,8, 9,10 },SECOND }}}" help="Complex type" />
    <Knob name="COMPLEX_KNOB3b" type="child_t" default="{{2,2,2,2,2},SECOND}" help="Complex type" />
    <Knob name="INTEGER_KNOB" type="uint32_t" default="100" help="Integer type" />
    <Knob name="BOOLEAN_KNOB" prettyname="Boolean Knob"  type="bool" default="true" help="Boolean type" />
    <Knob name="DOUBLE_KNOB" type="double" default="3.1415926" help="Double type" />
    <Knob name="FLOAT_KNOB" type="float" default="1.414" help="Float type" />

    <Knob name="INTEGER_KNOB2" type="uint32_t" default="89" help="Integer type" />
    <Knob name="BOOLEAN_KNOB2" type="bool" default="true" help="Boolean type" />
    <Knob name="DOUBLE_KNOB2" type="double" default="10.00281456" help="Double type" />
    <Knob name="FLOAT_KNOB233" type="float" default="4.56" help="Float type" />
  </Knobs>

</ConfigSchema>

=== jivahire-com/cpp-thread-safe-cache/config/knobs_config/kng_mscp_d2d_counter_knobs.xml
<ConfigSchema xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="configschema.xsd">

  <!-- Enum values are declared separately from the knobs.
       The same Enum can be used as the 'enumtype' of any number of EnumKnobs -->
  <Enums>
  </Enums>

  <Structs>
    <Struct name="d2d_counter_sync_knobs_t">
        <Member name="d2d_counter_sync_d0_cfg" type="d2d_counter_sync_d0_config_t" count="1" help="On boot config params (Die 0) for multi-die counter sync " />
        <Member name="d2d_counter_sync_d1_cfg" type="d2d_counter_sync_d1_config_t" count="1" help="On boot config params (Die 1) for multi-die counter sync " />
    </Struct>
  </Structs>

  <!-- namespace indicates the GUID namespace the values are stored in -->
  <Knobs namespace="{FE3ED49F-B173-41ED-9076-356661D46A42}">
    <!--  D2d counter Knobs -->
    <Knob name="d2d_counter_sync_knobs" type="d2d_counter_sync_knobs_t" help="D2D counter sync knob structure" />
    <Knob name="d2d_counter_sync_enable_die1" type="bool" default="true" help="Enable/Disable die 1 d2d counter sync logic" />
    <!-- End D2d counter Knobs -->
  </Knobs>

</ConfigSchema>

=== jivahire-com/cpp-thread-safe-cache/config/knobs_config/kng_mscp_system_config_knobs.xml
<!--
    Kingsgate MSCP system config knobs
-->
<ConfigSchema xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="configschema.xsd">

  <!-- Enum values are declared separately from the knobs.
       The same Enum can be used as the 'enumtype' of any number of EnumKnobs -->
  <Enums>
  </Enums>

  <Structs>
  </Structs>

  <!-- namespace indicates the GUID namespace the values are stored in -->
  <Knobs namespace="{FE3ED49F-B173-41ED-9076-356661D46A42}">
    <!-- Watchdog config knobs -->
    <Knob name="wdog_en" type="bool" default="false" help="Enable/Disable Watchdog." />
    <Knob name="wdog_timeout_s" type="uint32_t" default="5" help="Watchdog timeout in seconds." />
    <Knob name="wdog_counter_freq_Mhz" type="uint32_t" default="200" help="Watchdog counter decrement frequency in Mhz" />
    <Knob name="accel_boot_timeout_sec" type="uint32_t" default="20" help="Time in seconds. Time allowed for accel cores to boot and send an ACK to SCP. Once this timeout expires SCP sends a boot failed boot status code to HSP and then bug asserts." />
    <!-- end Watchdog config knobs -->
  </Knobs>

</ConfigSchema>

=== jivahire-com/cpp-thread-safe-cache/config/knobs_config/kng_mscp_gpio_config_knobs.xml
<ConfigSchema xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="configschema.xsd">

  <!-- Enum values are declared separately from the knobs.
       The same Enum can be used as the 'enumtype' of any number of EnumKnobs -->
  <Enums>
  </Enums>

  <Structs>
    <Struct name="uart_die_sel_t">
      <!-- Default routing, UART 1-> Die1, UART 2 -> Die1 --> <!-- GPIO Knobs for Die 1 Accel Debug
      <Member name="uart_die_sel" type="uint8_t" count="2" default="{1, 1}" help="Die to route Shared UARTs to" />  -->

      <!-- Default routing, UART 1-> Die0, UART 2 -> Die0 --> <!-- GPIO Knobs for Die 0 Accel Debug 
      <Member name="uart_die_sel" type="uint8_t" count="2" default="{0, 0}" help="Die to route Shared UARTs to" /> -->

      <!-- Default routing, UART 1-> Die0, UART 2 -> Die1 --> <!-- GPIO Knobs for to fetch both SCPs for flexibility  -->
      <Member name="uart_die_sel" type="uint8_t" count="2" default="{0, 0}" help="Die to route Shared UARTs to" />
    </Struct>
    <Struct name="uart_afm_cfg_prod_t">
      <Member name="uart0_afm" type="UART0_AFM_VAL" help="UART0 AFM" />
      <Member name="uart1_afm" type="UART1_AFM_VAL" help="UART1 AFM" />
      <Member name="uart2_afm" type="UART2_AFM_VAL" help="UART2 AFM" />
      <Member name="uart3_afm" type="UART3_AFM_VAL" help="UART3 AFM" />
    </Struct>
    <Struct name="uart_afm_cfg_d1_prod_t">
      <Member name="uart0_afm" type="D1_UART0_AFM_VAL" help="UART0 AFM" />
      <Member name="uart1_afm" type="D1_UART1_AFM_VAL" help="UART1 AFM" />
      <Member name="uart2_afm" type="D1_UART2_AFM_VAL" help="UART2 AFM" />
      <Member name="uart3_afm" type="D1_UART3_AFM_VAL" help="UART3 AFM" />
    </Struct>
  </Structs>
  
  <!-- namespace indicates the GUID namespace the values are stored in -->
  <Knobs namespace="{FE3ED49F-B173-41ED-9076-356661D46A42}">
    <Knob name="gpio_knobs" type="gpio_cfg_t" help="GPIO config knobs"/>
    
    <!-- Die 0 Config: Retain Default Config -->
    <Knob name="uart_afm_cfg_die0" type="uart_afm_cfg_prod_t" default="{D0_U0_HSP, D0_U1_SCP, D0_U2_MCP, D0_U3_AP_NS}" help="UART AFM config knobs for Die 0"/>
    <!-- Die 1 Config: Since UART 2 of Die 1 is routed to SCP, UART 1 of of Die 1 needs to be routed elsewhere, or SCP Die 1 Rx would not work. Hence routed by default to SDM -->
    <Knob name="uart_afm_cfg_die1" type="uart_afm_cfg_d1_prod_t" default="{D1_U0_HSP, D1_U1_SDM, D1_U2_SCP, 0}" help="UART AFM config knobs for Die 1"/>

    <Knob name="uart_die_cfg" type="uart_die_sel_t" help="Die Config for Shared UARTs (UART1 and UART2 respectively)"/>
    
    <Knob name="uart_mcp_reassign" type="bool" default="true" help="When true, reassigns MCP Die 0 CLI to use AP-NS UART" />
  </Knobs>

</ConfigSchema>
